-- KICKORA DATABASE SCHEMA — SUPABASE

create table if not exists matches (
  id bigint generated by default as identity primary key,
  external_id text unique not null,
  comp text,
  country text,
  match_date timestamptz,
  home_team text,
  away_team text,
  status text,
  goals_home int,
  goals_away int,
  raw jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists picks (
  id bigint generated by default as identity primary key,
  match_external_id text,
  match_label text,
  market text,
  selection text,
  probability numeric,
  odds numeric,
  stake numeric default 1,
  status text default 'pending' check (status in ('pending','won','lost','void')),
  result text,
  profit numeric,
  raw jsonb,
  created_at timestamptz default now(),
  settled_at timestamptz
);

create index if not exists idx_matches_external_id on matches(external_id);
create index if not exists idx_picks_match_external_id on picks(match_external_id);
create index if not exists idx_picks_status on picks(status);
create index if not exists idx_picks_market on picks(market);
